import Foundation

enum SettingsKeys {
    static let isEnabled = "settings.isEnabled"
    static let volume = "settings.volume"
    static let variation = "settings.variation"
    static let pitchVariation = "settings.pitchVariation"
    static let playKeyUp = "settings.playKeyUp"
    static let pressLevel = "settings.pressLevel"
    static let releaseLevel = "settings.releaseLevel"
    static let spaceLevel = "settings.spaceLevel"
    static let selectedProfile = "settings.selectedProfile"
    static let autoProfileTuningEnabled = "settings.autoProfileTuningEnabled"
    static let launchAtLogin = "settings.launchAtLogin"
    static let dynamicCompensationEnabled = "settings.dynamicCompensationEnabled"
    static let compensationStrength = "settings.compensationStrength"
    static let levelMacLow = "settings.levelMacLow"
    static let levelKbdLow = "settings.levelKbdLow"
    static let levelMacLowMid = "settings.levelMacLowMid"
    static let levelKbdLowMid = "settings.levelKbdLowMid"
    static let levelMacMid = "settings.levelMacMid"
    static let levelKbdMid = "settings.levelKbdMid"
    static let levelMacHighMid = "settings.levelMacHighMid"
    static let levelKbdHighMid = "settings.levelKbdHighMid"
    static let levelMacHigh = "settings.levelMacHigh"
    static let levelKbdHigh = "settings.levelKbdHigh"
    static let strictVolumeNormalizationEnabled = "settings.strictVolumeNormalizationEnabled"
    static let levelTuningMode = "settings.levelTuningMode"
    static let autoNormalizeTargetAt100 = "settings.autoNormalizeTargetAt100"
    static let typingAdaptiveEnabled = "settings.typingAdaptiveEnabled"
    static let stackModeEnabled = "settings.stackModeEnabled"
    static let stackDensity = "settings.stackDensity"
    static let layerThresholdSlam = "settings.layerThresholdSlam"
    static let layerThresholdHard = "settings.layerThresholdHard"
    static let layerThresholdMedium = "settings.layerThresholdMedium"
    static let minInterKeyGapMs = "settings.minInterKeyGapMs"
    static let releaseDuckingStrength = "settings.releaseDuckingStrength"
    static let releaseDuckingWindowMs = "settings.releaseDuckingWindowMs"
    static let releaseTailTightness = "settings.releaseTailTightness"
    static let limiterEnabled = "settings.limiterEnabled"
    static let limiterDrive = "settings.limiterDrive"
    static let outputDeviceBoosts = "settings.outputDeviceBoosts"
    static let autoOutputPresetEnabled = "settings.autoOutputPresetEnabled"
    static let perDeviceSoundProfileEnabled = "settings.perDeviceSoundProfileEnabled"
    static let appearanceMode = "settings.appearanceMode"
    static let perDeviceSoundSnapshots = "settings.perDeviceSoundSnapshots"
    static let perProfileSoundSnapshots = "settings.perProfileSoundSnapshots"
}
